package main

import (
	"edulite-api/database"

	"edulite-api/routes"

	"github.com/gin-gonic/gin"

	_ "edulite-api/docs" // import docs generated by swag

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title       Edulite API
// @version     1.0
// @description API untuk sistem Edulite
// @host        localhost:5555
// @BasePath    /
// @schemes     http
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	r := gin.Default()
	database.InitDB()

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Auth
	routes.AuthRoutes(r)

	routes.SiswaRoutes(r)

	r.Run(":5555")
}
